services:
  - type: web
    name: ai-code-reviewer-backend
    env: python
    rootDir: api              # 👈 tells Render to cd into api/
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: static_site
    name: ai-code-reviewer-frontend
    rootDir: frontend         # 👈 tells Render to cd into frontend/
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    env: node
    plan: free
